services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env