services:
  redis:
    image: redis:8.0
    ports:
      - "16379:6379"
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  postgres_database:
    image: postgres:17
    container_name: postgres_database
    ports:
      - "15431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres_database:
          condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

